### ISSUE TITLE
fly-rest appending ?null when GET is called without parameters

### ISSUE THREAD

**Issue by tulioccalazans** [softctrl/fly-rest#2]
Hi, please check the folowing code in **Request.Java**.
This library is appending "?null" when GET is called without parameters.
_Note: I'm using fly-rest 0.0.5_

`
public String getUrl() {
        StringBuilder url = new StringBuilder(this.mUrl);
        if(HttpMethod.GET.equals(this.getHttpMethod())) {
            url.append('?').append(this.getParameters());
        }
        return url.toString();
    }`

**Comment by softctrl** [comment]
hi @tulioccalazans , sorry for the delay. If you look at the newest version that problem was solved already.
the actual code of [Request.java](https://github.com/softctrl/fly-rest/blob/master/fly-rest/src/br/com/softctrl/net/rest/Request.java):

```Java
	/**
	 * 
	 * @return
	 */
	public String getUrl() {
		final StringBuilder url = new StringBuilder(this.mUrl);
		if (HttpMethod.GET.equals(this.getHttpMethod())) {
			if (this.mParameters != null && this.mParameters.size() > 0) {
				url.append('?').append(this.getStringParameters());
			}
		}
		return url.toString();
	}
```

how about update you library to use the newest version? What is keeping you away to update?

**Comment by tulioccalazans** [comment]
Thanks!
I couldn't update due the problem that the [Pull request](https://github.com/softctrl/fly-rest/pull/3) is fixing. The version _v0.0.5_ allows to customize and I can fix the problem that a relate there, but in the newest version it is not possible due restriction of final methods. So, may you check this pull request?
